"""Detection signals for Provenance Guard.

Milestone 3 implements Signal 1 only: an LLM "fluency / perplexity" judge backed by
Groq. Signal 2 (burstiness) and the multi-signal combiner arrive in Milestone 4.
"""

import json
import os

from groq import Groq

# Groq production model with JSON-mode support.
_MODEL = "llama-3.3-70b-versatile"
_client = None

_SYSTEM_PROMPT = """You are an AI-text detector. Judge how likely the user's text was \
generated by a large language model rather than written by a human.

Look for machine markers: unusually smooth/low-surprise phrasing, even tone, hedging, \
formulaic transitions ("Moreover,", "In conclusion,"), and an absence of idiosyncratic \
human voice. Human writing tends to be more uneven, specific, and surprising.

Respond with ONLY a JSON object of the form:
{"ai_likelihood": <integer 0-100>, "reason": "<one short sentence>"}
where 0 means almost certainly human and 100 means almost certainly AI. Do not include \
any text outside the JSON object."""

# Band thresholds (see planning.md §2). Shared so the combiner can reuse them in M4.
HUMAN_MAX = 0.35
AI_MIN = 0.65


def _get_client():
    global _client
    if _client is None:
        key = os.environ.get("GROQ_API_KEY")
        if not key:
            raise RuntimeError("GROQ_API_KEY is not set (check your .env)")
        _client = Groq(api_key=key)
    return _client


def llm_fluency(text):
    """Signal 1: ask Groq to rate AI-likelihood.

    Returns a dict {"score": float in [0,1], "reason": str} where score is P(AI),
    or None if the call fails or the response can't be parsed (the caller treats a
    None as "signal unavailable" and falls back to Uncertain).
    """
    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        score = max(0.0, min(1.0, float(data["ai_likelihood"]) / 100.0))
        reason = str(data.get("reason", "")).strip()
        return {"score": score, "reason": reason}
    except Exception as exc:  # network error, bad JSON, missing key, etc.
        print(f"[detector] llm_fluency failed: {exc}")
        return None


def attribution_from_score(score):
    """Map an AI-likelihood score in [0,1] to one of the three bands."""
    if score < HUMAN_MAX:
        return "likely_human"
    if score < AI_MIN:
        return "uncertain"
    return "likely_ai"


if __name__ == "__main__":
    # Quick standalone test (Milestone 3 step: test the signal before wiring it in).
    from dotenv import load_dotenv

    load_dotenv()
    samples = {
        "evocative human": (
            "The sun dipped below the horizon, painting the sky in hues of amber and "
            "rose. I sat on the porch, coffee in hand, watching the neighborhood slowly "
            "go quiet."
        ),
        "formulaic AI-ish": (
            "There are several key benefits to regular exercise. First, it improves "
            "cardiovascular health. Second, it enhances mental well-being. In conclusion, "
            "incorporating exercise into your routine is highly recommended."
        ),
        "one-liner": "ok sounds good lol",
    }
    for name, txt in samples.items():
        result = llm_fluency(txt)
        if result is None:
            print(f"{name:18s} -> SIGNAL UNAVAILABLE")
        else:
            print(
                f"{name:18s} -> score={result['score']:.2f} "
                f"({attribution_from_score(result['score'])}) :: {result['reason']}"
            )
