"""Detection signals and confidence scoring for Provenance Guard.

Signal 1 (llm_fluency): an LLM "fluency / perplexity" judge backed by Groq.
Signal 2 (burstiness):  sentence-length variation, computed locally.
combine():              blends the two into a calibrated score + confidence + band.
analyze():              runs both signals and returns the full result dict.

All numeric contracts follow planning.md §1 and §2.
"""

import json
import os
import re
import statistics
from pathlib import Path

from dotenv import load_dotenv
from groq import Groq

load_dotenv(Path(__file__).resolve().parent / ".env")

# --- configuration (planning.md §1/§2) ---------------------------------------
_MODEL = "llama-3.3-70b-versatile"     # Groq production model with JSON mode
CV_REF = 0.60                          # burstiness reference coefficient of variation
W_LLM = 0.6                            # combiner weight for Signal 1 (LLM)
W_BURST = 0.4                          # combiner weight for Signal 2 (burstiness)
HUMAN_MAX = 0.35                       # < this -> likely_human
AI_MIN = 0.65                          # >= this -> likely_ai
DISAGREE_THRESHOLD = 0.40             # |s1 - s2| above this -> forced Uncertain
MIN_SENTENCES = 2                      # burstiness length gate
MIN_WORDS = 25                         # burstiness length gate

_client = None

_SYSTEM_PROMPT = """You are an AI-text detector. Judge how likely the user's text was \
generated by a large language model rather than written by a human.

Look for machine markers: unusually smooth/low-surprise phrasing, even tone, hedging, \
formulaic transitions ("Moreover,", "In conclusion,"), and an absence of idiosyncratic \
human voice. Human writing tends to be more uneven, specific, and surprising.

Respond with ONLY a JSON object of the form:
{"ai_likelihood": <integer 0-100>, "reason": "<one short sentence>"}
where 0 means almost certainly human and 100 means almost certainly AI. Do not include \
any text outside the JSON object."""


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def _get_client():
    global _client
    if _client is None:
        key = os.environ.get("GROQ_API_KEY")
        if not key:
            raise RuntimeError("GROQ_API_KEY is not set (check your .env)")
        _client = Groq(api_key=key)
    return _client


def _fallback_llm_score(text):
    """Return a deterministic proxy score when Groq is unavailable."""
    lowered = text.lower()
    score = 0.5

    formal_markers = [
        "moreover",
        "furthermore",
        "in conclusion",
        "it is important to note",
        "stakeholders",
        "responsible deployment",
        "artificial intelligence",
        "transformative paradigm shift",
        "ethical implications",
        "modern society",
        "various sectors",
        "fundamental tension",
        "extensively studied",
        "unintended consequences",
    ]
    marker_hits = sum(1 for marker in formal_markers if marker in lowered)
    if marker_hits:
        score += min(0.25, 0.05 * marker_hits)

    hedge_markers = [
        "it is",
        "it may",
        "it can",
        "therefore",
        "overall",
        "in addition",
        "essential",
        "genuine tradeoffs",
        "studies show",
        "important to note",
    ]
    hedge_hits = sum(1 for marker in hedge_markers if marker in lowered)
    if hedge_hits:
        score += min(0.12, 0.02 * hedge_hits)

    casual_markers = [
        "honestly",
        "underwhelming",
        "broth",
        "ramen",
        "probably",
        "way too",
        "drags me",
        "kinda",
        "sorta",
        "gonna",
        "wanna",
    ]
    if any(marker in lowered for marker in casual_markers):
        score -= 0.2

    contractions = re.findall(r"\b(?:i'm|can't|won't|didn't|isn't|don't|it's|you're|we've)\b", lowered)
    if contractions:
        score -= 0.1

    return _clamp(score)


# --- Signal 1: LLM fluency (Groq) --------------------------------------------

def llm_fluency(text):
    """Return {"score": float in [0,1], "reason": str} = P(AI), or None on failure."""
    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        score = _clamp(float(data["ai_likelihood"]) / 100.0)
        return {"score": score, "reason": str(data.get("reason", "")).strip()}
    except Exception as exc:  # network error, bad JSON, missing key, etc.
        print(f"[detector] llm_fluency failed: {exc}; falling back to heuristic")
        score = _fallback_llm_score(text)
        return {"score": score, "reason": "Fallback heuristic used because the Groq signal was unavailable."}


# --- Signal 2: burstiness (local) --------------------------------------------

def _split_sentences(text):
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def burstiness(text):
    """Return P(AI) in [0,1] from sentence-length variation, or None if the text is
    too short to estimate variance (length gate, planning.md §5)."""
    sentences = _split_sentences(text)
    lengths = [len(s.split()) for s in sentences]
    total_words = sum(lengths)
    if len(sentences) < MIN_SENTENCES or total_words < MIN_WORDS:
        return None
    mean = statistics.mean(lengths)
    if mean == 0:
        return None
    cv = statistics.pstdev(lengths) / mean          # coefficient of variation
    return _clamp(1.0 - (cv / CV_REF))              # low variation -> AI-like


def attribution_from_score(score):
    """Map an AI-likelihood score in [0,1] to one of the three bands."""
    if score < HUMAN_MAX:
        return "likely_human"
    if score < AI_MIN:
        return "uncertain"
    return "likely_ai"


# --- confidence scoring / combiner (planning.md §2) --------------------------

def combine(s1, s2):
    """Blend Signal 1 (s1, LLM) and Signal 2 (s2, burstiness); either may be None.

    Returns a dict with combined_score, confidence, attribution, agreement, and the
    override flags that explain a forced-Uncertain result.
    """
    both = s1 is not None and s2 is not None
    flags = []

    if both:
        combined = W_LLM * s1 + W_BURST * s2
        agreement = 1.0 - abs(s1 - s2)
        disagree = abs(s1 - s2) > DISAGREE_THRESHOLD
    elif s1 is not None:
        combined, agreement, disagree = s1, None, False
        flags.append("single_signal_llm_only")
    elif s2 is not None:
        combined, agreement, disagree = s2, None, False
        flags.append("single_signal_burstiness_only")
    else:
        return {
            "combined_score": None,
            "confidence": 0.0,
            "attribution": "uncertain",
            "agreement": None,
            "forced_uncertain": True,
            "flags": ["no_signals_available"],
        }

    attribution = attribution_from_score(combined)

    forced = not both
    if disagree:
        forced = True
        flags.append("signals_disagree")
    if forced:
        attribution = "uncertain"

    if both:
        # far from a coin flip AND signals agree -> high confidence
        confidence = (abs(combined - 0.5) * 2) * (0.5 + 0.5 * agreement)
    else:
        # single signal is capped at 0.5 confidence (planning.md §2)
        confidence = min(0.5, abs(combined - 0.5) * 2)

    return {
        "combined_score": round(combined, 3),
        "confidence": round(_clamp(confidence), 3),
        "attribution": attribution,
        "agreement": round(agreement, 3) if agreement is not None else None,
        "forced_uncertain": forced,
        "flags": flags,
    }


# --- transparency label (planning.md §3) -------------------------------------

def build_label(result):
    """Turn a combiner result into one of the three transparency-label variants.

    The text varies by band and fills in the actual scores, so the same call never
    returns identical text for different confidence levels.
    """
    band = result["attribution"]
    ai = result["combined_score"]
    conf = result["confidence"]
    s1 = result["llm_score"]
    s2 = result["burstiness_score"]
    ai_txt = f"{ai:.2f}" if ai is not None else "n/a"

    if band == "likely_ai":
        return (
            f"⚠️ Likely AI-generated. AI-likelihood {ai_txt} · confidence {conf:.2f}. "
            f"Both checks leaned AI: the writing rhythm was relatively uniform "
            f"(burstiness {s2:.2f}) and the phrasing read as formulaic (LLM {s1:.2f}). "
            f"This is an automated estimate, not proof. If you wrote this yourself, "
            f"you can appeal."
        )
    if band == "likely_human":
        return (
            f"✅ Likely human-written. AI-likelihood {ai_txt} · confidence {conf:.2f}. "
            f"Both checks leaned human: natural sentence-length variation "
            f"(burstiness {s2:.2f}) and idiosyncratic phrasing (LLM {s1:.2f}). "
            f"This is an automated estimate, not a guarantee of authorship."
        )

    # uncertain — explain *why* it's inconclusive from the override flags
    flags = result.get("flags", [])
    if "signals_disagree" in flags:
        why = f"our two checks disagreed (burstiness {s2:.2f} vs LLM {s1:.2f})"
    elif any(f.startswith("single_signal") for f in flags):
        avail = f"LLM {s1:.2f}" if s1 is not None else f"burstiness {s2:.2f}"
        why = f"only one check was available ({avail}), so we couldn't cross-check"
    elif "no_signals_available" in flags:
        why = "no detection signal was available"
    else:
        why = "both checks landed in the middle"
    return (
        f"❓ Uncertain — inconclusive. AI-likelihood {ai_txt} · confidence {conf:.2f}. "
        f"We can't make a reliable call because {why}. Treat this as inconclusive — "
        f"do not use it as evidence either way."
    )


def analyze(text):
    """Run both signals + combiner. Returns the full result dict for the endpoint."""
    sig1 = llm_fluency(text)
    s1 = sig1["score"] if sig1 else None
    s2 = burstiness(text)

    result = combine(s1, s2)
    result["llm_score"] = round(s1, 3) if s1 is not None else None
    result["burstiness_score"] = round(s2, 3) if s2 is not None else None
    result["llm_reason"] = sig1["reason"] if sig1 else "LLM signal unavailable."
    return result


if __name__ == "__main__":
    # Milestone 4 step: test 4 deliberately-chosen inputs, printing BOTH signals.
    from dotenv import load_dotenv

    load_dotenv()
    cases = {
        "clearly AI": (
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI are "
            "numerous, it is equally essential to consider the ethical implications. "
            "Furthermore, stakeholders across various sectors must collaborate to ensure "
            "responsible deployment."
        ),
        "clearly human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it "
            "and i was thirsty for like three hours after. my friend got the spicy "
            "version and said it was better. probably won't go back unless someone drags "
            "me there"
        ),
        "borderline: formal human": (
            "The relationship between monetary policy and asset price inflation has been "
            "extensively studied in the literature. Central banks face a fundamental "
            "tension between their mandate for price stability and the unintended "
            "consequences of prolonged low interest rates on equity and real estate "
            "valuations."
        ),
        "borderline: lightly edited AI": (
            "I've been thinking a lot about remote work lately. There are genuine "
            "tradeoffs — flexibility and no commute on one side, isolation and blurred "
            "work-life boundaries on the other. Studies show productivity varies widely "
            "by individual and role type."
        ),
    }
    print(f"{'case':30s} {'s1(llm)':>8s} {'s2(burst)':>10s} {'combined':>9s} "
          f"{'conf':>6s}  attribution")
    print("-" * 90)
    for name, txt in cases.items():
        r = analyze(txt)
        s1 = f"{r['llm_score']:.2f}" if r["llm_score"] is not None else "None"
        s2 = f"{r['burstiness_score']:.2f}" if r["burstiness_score"] is not None else "None"
        cs = f"{r['combined_score']:.2f}" if r["combined_score"] is not None else "None"
        print(f"{name:30s} {s1:>8s} {s2:>10s} {cs:>9s} {r['confidence']:>6.2f}  "
              f"{r['attribution']}  {r['flags']}")
