"""User-facing transparency labels for provenance assessments."""

from typing import Any


def generate_transparency_label(confidence: float) -> dict[str, Any]:
    """Map a human-authorship confidence score to the planned label variant."""
    if isinstance(confidence, bool) or not isinstance(confidence, (int, float)):
        raise ValueError("confidence must be a number between 0.0 and 1.0")
    if not 0.0 <= confidence <= 1.0:
        raise ValueError("confidence must be a number between 0.0 and 1.0")

    if confidence <= 0.35:
        return {
            "attribution": "likely_ai",
            "label": "High-Confidence AI",
            "message": (
                "This content was likely generated by an AI tool. Our systems detected highly "
                "predictable language patterns and uniform sentence structures typical of "
                "machine generation."
            ),
        }
    if confidence <= 0.65:
        return {
            "attribution": "uncertain",
            "label": "Uncertain",
            "message": (
                "This content shows mixed signals. It contains structural patterns common to both "
                "human writers and AI tools, so we cannot make a definitive classification."
            ),
        }
    return {
        "attribution": "likely_human",
        "label": "High-Confidence Human",
        "message": (
            "This content was likely written by a human. Our systems detected natural variations "
            "in sentence structure and vocabulary."
        ),
    }
